### ISSUE TITLE
Getting Attribute error when running host-guest calculations on PBS

### ISSUE THREAD

**Issue by jeff231li** [openforcefield/openff-evaluator#313]
I'm running into a problem when I run `Evaluator` on a cluster with PBS for the pAPRika host-guest calculations. I checked the working folder and `Evaluator` calculates the binding free energy. However, the program quits afterward (after all workers have completed their job) and spits out the following error:

```python
Traceback (most recent call last):
  File "run_pbs.py", line 118, in <module>
    main()
  File "run_pbs.py", line 110, in main
    root_directory="workflow", calculation_backend=calculation_backend,
  File "/projects/gilson-kirkwood/jsetiadi/anaconda3_tscc/envs/evaluator/lib/python3.7/site-packages/distributed/client.py", line 225, in result
    raise exc.with_traceback(tb)
  File "/projects/gilson-onsager/jsetiadi/openff-evaluator/openff/evaluator/backends/dask.py", line 477, in _wrapped_function
    return_value = _Multiprocessor.run(function, *args, **kwargs) 
  File "/projects/gilson-onsager/jsetiadi/openff-evaluator/openff/evaluator/backends/dask.py", line 169, in run
    raise return_value[0]
multiprocessing.managers.RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/projects/gilson-kirkwood/jsetiadi/anaconda3_tscc/envs/evaluator/lib/python3.7/multiprocessing/managers.py", line 234, in serve_client
    request = recv()
  File "/projects/gilson-kirkwood/jsetiadi/anaconda3_tscc/envs/evaluator/lib/python3.7/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/projects/gilson-onsager/jsetiadi/openff-evaluator/openff/evaluator/attributes/attributes.py", line 226, in __setstate__
    self._set_value(name, state[name])
  File "/projects/gilson-onsager/jsetiadi/openff-evaluator/openff/evaluator/attributes/attributes.py", line 166, in _set_value
    attribute._set_value(self, value)
  File "/projects/gilson-onsager/jsetiadi/openff-evaluator/openff/evaluator/attributes/attributes.py", line 361, in _set_value
    f"The {self._private_attribute_name[1:]} attribute can only accept "
ValueError: The value attribute can only accept values of type <class 'pint.measurement.Measurement'>
---------------------------------------------------------------------------
```

I don't get this error when I run the calculations on a local cluster. Any idea what's wrong?
[host_guest_evaluator.zip](https://github.com/openforcefield/openff-evaluator/files/5432214/host_guest_evaluator.zip)

**Comment by SimonBoothroyd** [comment]
There is a bug in newer version of `pint` unfortunately which causes some of its objects to be incorrectly serialised by `dask`. For now this can be resolved by making sure to only install `pint >=0.10.1,<0.15`.

This can be done by running `conda install -c conda-forge "pint >=0.10.1,<0.15"`

**Comment by SimonBoothroyd** [comment]
If that doesn't resolve the issue for you, please feel free to re-open this!

**Comment by jeff231li** [comment]
Thank you! It works with `pint 0.14`.
