### ISSUE TITLE
Random halting of estimations (experiments/solvent2.nc)

### ISSUE THREAD

**Issue by jaketanderson** [openforcefield/openff-evaluator#469]
I'm wondering if anyone could point me in the right direction here. I'm running a force field optimization and every iteration I evaluate the HFEs of ~14 compounds and the host-guest BFEs of a few compounds. I'm noticing that seemingly at random I get this error which is fatal and breaks the evaluation:

> 2022-09-11 22:01:27.118 INFO     Launching batch dce72e2e48194733b1408ccb70406d33 using the SimulationLayer layer
2022-09-11 22:01:27.118 INFO     Launching batch dce72e2e48194733b1408ccb70406d33 using the SimulationLayer layer
2022-09-11 22:01:27.118 INFO     Launching batch dce72e2e48194733b1408ccb70406d33 using the SimulationLayer layer
2022-09-11 22:01:27.152 INFO     Building workflow 0 of 1
2022-09-11 22:01:27.152 INFO     Building workflow 0 of 1
2022-09-11 22:01:27.152 INFO     Building workflow 0 of 1
2022-09-11 22:01:41.219 INFO     Finished server request ae89cc05de5b449f881e346d19e60487
2022-09-11 22:01:41.219 INFO     Finished server request ae89cc05de5b449f881e346d19e60487
2022-09-11 22:01:41.219 INFO     Finished server request ae89cc05de5b449f881e346d19e60487
2022-09-11 22:02:09.694 INFO     Exceptions were raised while executing batch 03c8d5a4cf634b7096f5ae444ee8e50f
2022-09-11 22:02:09.694 INFO     Exceptions were raised while executing batch 03c8d5a4cf634b7096f5ae444ee8e50f
2022-09-11 22:02:09.694 INFO     Exceptions were raised while executing batch 03c8d5a4cf634b7096f5ae444ee8e50f
2022-09-11 22:02:09.694 INFO     b4606556d3dd4500afd25471ec48f58f|conditional_group failed to execute.

> Traceback (most recent call last):
  File "/gpfs/jta002/anaconda3/envs/forcebalance/lib/python3.8/site-packages/openff/evaluator/workflow/protocols.py", line 1260, in _execute_protocol
    protocol.execute(directory, available_resources)
  File "/gpfs/jta002/anaconda3/envs/forcebalance/lib/python3.8/site-packages/openff/evaluator/workflow/protocols.py", line 719, in execute
    self._execute(directory, available_resources)
  File "/gpfs/jta002/anaconda3/envs/forcebalance/lib/python3.8/site-packages/openff/evaluator/protocols/groups.py", line 239, in _execute
    super(ConditionalGroup, self)._execute(directory, available_resources)
...
  File "/gpfs/jta002/anaconda3/envs/forcebalance/lib/python3.8/site-packages/openmmtools/multistate/multistatereporter.py", line 139, in __init__
    self.open(open_mode)
  File "/gpfs/jta002/anaconda3/envs/forcebalance/lib/python3.8/site-packages/openmmtools/multistate/multistatereporter.py", line 279, in open
    self._storage_analysis = self._open_dataset_robustly(self._storage_analysis_file_path,
  File "/gpfs/jta002/anaconda3/envs/forcebalance/lib/python3.8/site-packages/openmmtools/multistate/multistatereporter.py", line 383, in _open_dataset_robustly
    raise IOError(f"{args[0]} does not exist")
OSError: experiments/solvent2.nc does not exist

After this `experiments/solvent2.nc does not exist` error in the conditional_group, I receive a few `Particle position is NaN` errors in the release_thermalization group. Is the release_thermalization part of both evaluation types? If so, this might just be an error with HFEs. Otherwise it could be more general.

One fix I tried was creating an empty `experiments` directory in the directory of the python script. Unfortunately that did not work. I also tried scaling up and down the number of Dask workers on the SLURM-based cluster I'm using and that didn't seem to have an effect.

**Comment by mattwthompson** [comment]
Is this the part of Evaluator that uses Yank?

**Comment by jaketanderson** [comment]
> Is this the part of Evaluator that uses Yank?

It seems so, yeah.

**Comment by mattwthompson** [comment]
Judging just by the [order in the protocol](https://github.com/openforcefield/openff-evaluator/blob/2fa7453b1f43eae96d7559098d3521fe8750928e/openff/evaluator/properties/binding.py#L720-L733), I can't do much more than guess that an earlier step failed - but you more or less already know that, and that's not useful diagnostically. Sorry I'm not able to help here at first glance. I assume you've already been in touch with @jeff231li who is likely more familiar with this code?

**Comment by jaketanderson** [comment]
Yes, Jeff is very familiar with the code. I just figured I'd also make an issue here to cast a wide net on the off chance this has happened before :)

**Comment by jaketanderson** [comment]
@jeff231li was able to solve this issue by fixing my broken dask configuration file. The cluster wasn't being assigned work properly so no wonder the evaluations had estimation errors. I'm actually surprised they were able to work at all!
