### ISSUE TITLE
Star imports misconfigured

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-evaluator#498]
All module-level `__init__.py` files have `__all__` defined, but [using classes](https://github.com/openforcefield/openff-evaluator/blob/v0.4.2/openff/evaluator/forcefield/__init__.py) and not strings as they're supposed to be. I'm not sure star imports ever worked?

```python3
>>> from openff.evaluator.forcefield import *
Warning on use of the timeseries module: If the inherent timescales of the system are long compared to those being analyzed, this statistical inefficiency may be an underestimate.  The estimate presumes the use of many statistically independent samples.  Tests should be performed to assess whether this condition is satisfied.   Be cautious in the interpretation of the data.
/Users/mattthompson/software/openff-evaluator/openff/evaluator/protocols/yank.py:62: YankDeprecrationWarning: The YANK protocol has been deprecated and will be removed in a future release. Free energy calculations will be enabled by Perses in the future.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1073, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 1069, in _handle_fromlist
TypeError: Item in openff.evaluator.forcefield.__all__ must be str, not ABCMeta

**Comment by mattwthompson** [comment]
Oh, this was all to make import path shorter, not to enable star imports. Hmm.
