### ISSUE TITLE
Pint removed upcast_types = [] from pint.compat

### ISSUE THREAD

**Issue by aehogan** [openforcefield/openff-evaluator#525]
**Describe the bug**
Attribute error pint.compat.upcast_types as it was removed from pint >= 0.21

**To Reproduce**
Import error with from openff.evaluator.substances import Substance
with pint=0.21 or pint=0.22

**Output**
Traceback (most recent call last):
  File "/home/aehogan2/Documents/new_force_fields/openmm/eval_phahst/collate.py", line 10, in <module>
    from openff.evaluator.substances import Substance
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/site-packages/openff/evaluator/__init__.py", line 12, in <module>
    register_default_plugins()
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/site-packages/openff/evaluator/plugins.py", line 21, in register_default_plugins
    importlib.import_module("openff.evaluator.properties")
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/site-packages/openff/evaluator/properties/__init__.py", line 1, in <module>
    from .binding import HostGuestBindingAffinity
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/site-packages/openff/evaluator/properties/binding.py", line 10, in <module>
    from openff.evaluator.layers import register_calculation_schema
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/site-packages/openff/evaluator/layers/__init__.py", line 1, in <module>
    from .layers import CalculationLayer, CalculationLayerResult, CalculationLayerSchema
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/site-packages/openff/evaluator/layers/layers.py", line 18, in <module>
    from openff.evaluator.storage.data import BaseStoredData, StoredSimulationData
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/site-packages/openff/evaluator/storage/__init__.py", line 1, in <module>
    from .storage import StorageBackend  # isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/site-packages/openff/evaluator/storage/storage.py", line 11, in <module>
    from openff.evaluator.storage.data import (
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/site-packages/openff/evaluator/storage/data.py", line 9, in <module>
    from openff.evaluator.forcefield import ForceFieldSource
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/site-packages/openff/evaluator/forcefield/__init__.py", line 7, in <module>
    from .gradients import ParameterGradient, ParameterGradientKey
  File "/home/aehogan2/miniconda3/envs/openff_smirnoff_plugins/lib/python3.11/site-packages/openff/evaluator/forcefield/gradients.py", line 173, in <module>
    pint.compat.upcast_types.append(ParameterGradient)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pint.compat' has no attribute 'upcast_types'. Did you mean: 'is_upcast_type'?

**Computing environment (please complete the following information):**
Linux 64
pint                      0.21               pyhd8ed1ab_0    conda-forge
openff-amber-ff-ports     0.0.3              pyh6c4a22f_0    conda-forge
openff-evaluator          0.3.11             pyhd8ed1ab_0    conda-forge
openff-evaluator-base     0.3.11             pyhd8ed1ab_0    conda-forge
openff-forcefields        2023.08.0          pyh1a96a4e_0    conda-forge
openff-interchange        0.3.13             pyhd8ed1ab_0    conda-forge
openff-interchange-base   0.3.13             pyhd8ed1ab_0    conda-forge
openff-models             0.1.0              pyh1a96a4e_1    conda-forge
openff-toolkit            0.14.3             pyhd8ed1ab_0    conda-forge
openff-toolkit-base       0.14.3             pyhd8ed1ab_0    conda-forge
openff-units              0.2.1              pyh1a96a4e_0    conda-forge
openff-utilities          0.1.9              pyh1a96a4e_0    conda-forge

**Comment by aehogan** [comment]
Fixed by pinning pint=0.20

**Comment by mattwthompson** [comment]
That's [pinned](https://github.com/conda-forge/openff-evaluator-feedstock/blob/3a8fe87deca6ad964f91008fc7df91400412eca5/recipe/meta.yaml#L47) in deployment - you must be using a development install?

**Comment by aehogan** [comment]
using the test_env.yaml in smirnoff_plugins but conda installed openff-evaluator after that
