### ISSUE TITLE
Update calls to Simulation.MinimizeEnergy to provide tolerance as force, not energy

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-evaluator#530]
**Describe the bug**
@leeping reported that, using a dev build of OpenMM from its latest `main` branch, there was an error when calling `Simulation.MinimizeEnergy`:

```
E           ValueError: Some properties could not be estimated:
E
E           a4953f6dba364b3ca1bcf85d63a43e70|energy_minimisation_gas failed to execute.
E
E           Traceback (most recent call last):
E             File "/home/leeping/opt/miniconda3/envs/main/lib/python3.9/site-packages/openff/evaluator/workflow/protocols.py", line 1193, in _execute_protocol
E               protocol.execute(directory, available_resources)
E             File "/home/leeping/opt/miniconda3/envs/main/lib/python3.9/site-packages/openff/evaluator/workflow/protocols.py", line 680, in execute
E               self._execute(directory, available_resources)
E             File "/home/leeping/opt/miniconda3/envs/main/lib/python3.9/site-packages/openff/evaluator/protocols/openmm.py", line 350, in _execute
E               simulation.minimizeEnergy(to_openmm(self.tolerance), self.max_iterations)
E             File "/home/leeping/opt/miniconda3/envs/main/lib/python3.9/site-packages/openmm/app/simulation.py", line 143, in minimizeEnergy
E               mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations, reporter)
E             File "/home/leeping/opt/miniconda3/envs/main/lib/python3.9/site-packages/openmm/openmm.py", line 1478, in minimize
E               tolerance = tolerance.value_in_unit(unit.kilojoules_per_mole/unit.nanometer)
E             File "/home/leeping/opt/miniconda3/envs/main/lib/python3.9/site-packages/openmm/unit/quantity.py", line 626, in value_in_unit
E               val = self.in_units_of(unit)
E             File "/home/leeping/opt/miniconda3/envs/main/lib/python3.9/site-packages/openmm/unit/quantity.py", line 662, in in_units_of
E               raise TypeError('Unit "%s" is not compatible with Unit "%s".' % (self.unit, other_unit))
E           TypeError: Unit "kilojoule/mole" is not compatible with Unit "kilojoule/(nanometer*mole)".
```

To fix, the tolerance in [this line](https://github.com/openforcefield/openff-evaluator/blob/e95b28b41aa5eab4378e79ae2c8703f59fe63c37/openff/evaluator/protocols/openmm.py#L350) will need to be provided as a force, not an energy.

**Comment by mattwthompson** [comment]
Probably a type mismatch https://github.com/openforcefield/openff-evaluator/blob/e95b28b41aa5eab4378e79ae2c8703f59fe63c37/openff/evaluator/protocols/simulation.py#L37-L41

**Comment by mattwthompson** [comment]
OpenMM doesn't actually check the dimensionality of that argument. This block runs without error, even though I expected it to error:


```python3
import openmm
import openmm.unit


simulation = interchange.to_openmm_simulation(
    integrator=openmm.LangevinMiddleIntegrator(
        300 * openmm.unit.kelvin,
        1 / openmm.unit.picosecond,
        1.0,
    )
)

simulation.minimizeEnergy(10 * openmm.unit.kilojoule_per_mole / openmm.unit.nanometer)
simulation.minimizeEnergy(10 * openmm.unit.kilojoule_per_mole)
simulation.minimizeEnergy(10 * openmm.unit.picosecond)
simulation.minimizeEnergy(10 * openmm.unit.kelvin)

**Comment by mattwthompson** [comment]
This one is confusing to me. Switching the units over to $\dfrac{kJ}{mol * nm}$ might fix it, but if that was the problem the above code block should be throwing errors (and this would have been an issue years ago).

I don't think it's likely that the conversion drops the nanometer in the denominator:

```python3
In [1]: import openmm.unit

In [2]: 10 * openmm.unit.kilojoule_per_mole / openmm.unit.nanometer
Out[2]: Quantity(value=10, unit=kilojoule/(nanometer*mole))

In [3]: from openff.units import Quantity, unit

In [4]: from openff.units.openmm import to_openmm

In [5]: to_openmm(Quantity("10 kilojoule/mol/nanometer"))
Out[5]: Quantity(value=10.0, unit=kilojoule/(nanometer*mole))

In [6]: Quantity("10 kilojoule/mol/nanometer").to_openmm()
Out[6]: Quantity(value=10.0, unit=kilojoule/(nanometer*mole))

**Comment by mattwthompson** [comment]
This can be reproduced with `openmm==8.1.0beta`, but no earlier versions. Until builds were made of this release, I didn't have an easy way of accessing these changes. This behavior change is attributed to https://github.com/openmm/openmm/pull/2972, though I don't believe that's the cause. Previously, no unit checks happened and I don't see how changing the default value of an argument would introduce _new_ logic. Anyway,

```python
from openff.toolkit import Molecule, ForceField

import openmm
import openmm.unit


molecule = Molecule.from_smiles("OC[C@H](O)[C@H]1OC(=O)C(O)=C1O")
molecule.generate_conformers()

interchange = ForceField("openff-2.1.0.offxml").create_interchange(molecule.to_topology())

simulation = interchange.to_openmm_simulation(
    integrator=openmm.LangevinMiddleIntegrator(
        300 * openmm.unit.kelvin,
        1 / openmm.unit.picosecond,
        1.0,
    )
)

simulation.minimizeEnergy(10 * openmm.unit.kilojoule_per_mole / openmm.unit.nanometer)
simulation.minimizeEnergy(10 * openmm.unit.kilojoule_per_mole)
simulation.minimizeEnergy(10 * openmm.unit.picosecond)
simulation.minimizeEnergy(10 * openmm.unit.kelvin)
```
```
$ python repro.py
Traceback (most recent call last):
  File "/Users/mattthompson/software/openff-evaluator/repro.py", line 21, in <module>
    simulation.minimizeEnergy(10 * openmm.unit.kilojoule_per_mole)
  File "/Users/mattthompson/mambaforge/envs/openmm-beta/lib/python3.11/site-packages/openmm/app/simulation.py", line 143, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations, reporter)
  File "/Users/mattthompson/mambaforge/envs/openmm-beta/lib/python3.11/site-packages/openmm/openmm.py", line 12476, in minimize
    tolerance = tolerance.value_in_unit(unit.kilojoules_per_mole/unit.nanometer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattthompson/mambaforge/envs/openmm-beta/lib/python3.11/site-packages/openmm/unit/quantity.py", line 626, in value_in_unit
    val = self.in_units_of(unit)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattthompson/mambaforge/envs/openmm-beta/lib/python3.11/site-packages/openmm/unit/quantity.py", line 662, in in_units_of
    raise TypeError('Unit "%s" is not compatible with Unit "%s".' % (self.unit, other_unit))
TypeError: Unit "kilojoule/mole" is not compatible with Unit "kilojoule/(nanometer*mole)".
